/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package course.management.system;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class CourseManagementSystemApplicationTest {

    @Test
    void contextLoads() {
    }
}
