/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package course.management.system;

public class CourseManagementSystemApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new CourseManagementSystemApplication().getGreeting());
    }
}
